/**
 * Investment Auto — icon set generator.
 *
 * Reads the Lucide icon *node* data (shipped by `lucide-static`, a dev-only
 * dependency) and emits a static module containing only the icons this shell
 * actually uses, then splices it into `lib/client.js` between the ICONS markers.
 *
 * Why generate instead of importing a component library:
 *
 *   The client half is a pre-compiled `window.__ModuleLoader__.load({id,factory})`
 *   bundle with no bundler in the loop, and the DSH loader only resolves `react`
 *   and `react/jsx-runtime`. Pulling in `lucide-react` would mean introducing a
 *   build step that rewrites that module contract — a large risk for a purely
 *   cosmetic gain. Generating the icon data at build time delivers the same
 *   result (a real, maintained icon library; only the icons used; fully offline)
 *   while leaving the runtime contract untouched and adding zero runtime
 *   dependency.
 *
 * Usage:
 *   node app/plugins/dsh-product-shell/scripts/generate-icons.mjs           # write
 *   node app/plugins/dsh-product-shell/scripts/generate-icons.mjs --check    # verify only
 *
 * `--check` is wired into release-check so a stale generated block cannot ship.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pluginRoot = join(here, "..");
const appRoot = join(pluginRoot, "..", "..");
const clientPath = join(pluginRoot, "lib", "client.js");
const nodesPath = join(appRoot, "node_modules", "lucide-static", "icon-nodes.json");

/**
 * Icons this shell uses. Names are Lucide icon ids (kebab-case). Keeping the
 * list explicit is what makes the output tree-shaken: 14 icons instead of 2130.
 */
const ICONS = {
  layoutDashboard: "layout-dashboard",
  messageSquare: "message-square",
  radar: "radar",
  workflow: "workflow",
  settings: "settings",
  sparkles: "sparkles",
  play: "play",
  square: "square",
  refreshCw: "refresh-cw",
  download: "download",
  chevronDown: "chevron-down",
  checkCircle: "circle-check",
  alertTriangle: "triangle-alert",
  xCircle: "circle-x",
};

// Attributes Lucide omits from node data because they are defaults on its own
// <svg> wrapper. We render the nodes inside our own <svg>, so they must be
// supplied here or the strokes render wrong (filled, or hairline-thin).
const SVG_DEFAULTS = 'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

function escapeAttr(value) {
  return String(value).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Render one icon's node array to an SVG fragment string. */
function renderIcon(nodes) {
  const list = Array.isArray(nodes) ? nodes : [nodes];
  const parts = [];
  for (const node of list) {
    // Shape seen in icon-nodes.json: [tagName, attributes] or { value: [...] }.
    const raw = Array.isArray(node?.value) ? node.value : node;
    if (!Array.isArray(raw) || typeof raw[0] !== "string") continue;
    const [tag, attributes] = raw;
    const attrs = Object.entries(attributes ?? {})
      .filter(([, value]) => value !== undefined && value !== null)
      .map(([key, value]) => `${key}="${escapeAttr(value)}"`)
      .join(" ");
    parts.push(attrs ? `<${tag} ${attrs}/>` : `<${tag}/>`);
  }
  return parts.join("");
}

/**
 * Dominant line ending of a text, or null when it has none.
 *
 * The repo runs with core.autocrlf=true, so a checked-out client.js is CRLF on
 * Windows and LF in CI. Hard-coding one of them makes the generated region
 * disagree with the file it is spliced into, and then `--check` reports STALE
 * forever on the other platform — the block is byte-different without a single
 * icon having changed.
 */
function newlineOf(text) {
  const crlf = (text.match(/\r\n/g) || []).length;
  const lf = (text.match(/\n/g) || []).length;
  if (lf === 0) return null;
  return crlf * 2 >= lf ? "\r\n" : "\n";
}

function build(eol) {
  if (!existsSync(nodesPath)) {
    console.error(`generate-icons: lucide-static not found at ${nodesPath}`);
    console.error("generate-icons: run `npm install` in app/ first (it is a devDependency).");
    process.exit(1);
  }
  const nodes = JSON.parse(readFileSync(nodesPath, "utf-8"));
  const entries = [];
  const missing = [];
  for (const [key, id] of Object.entries(ICONS)) {
    const data = nodes[id];
    if (!data) { missing.push(id); continue; }
    entries.push(`\t"${key}": '<svg ${SVG_DEFAULTS} viewBox="0 0 24 24">${renderIcon(data)}</svg>'`);
  }
  if (missing.length > 0) {
    console.error(`generate-icons: unknown Lucide icon id(s): ${missing.join(", ")}`);
    process.exit(1);
  }
  const block = [
    "\t\t/* ICONS:START — generated by scripts/generate-icons.mjs; do not edit by hand. */",
    `\t\t// Source: lucide-static@${JSON.parse(readFileSync(join(appRoot, "node_modules", "lucide-static", "package.json"), "utf-8")).version}` +
      ` (${entries.length} of ${Object.keys(nodes).length} icons)`,
    "\t\tconst ICON_SVG = {",
    entries.join("," + eol),
    "\t\t};",
    "",
    "\t\t/** Render one icon as an inline <svg> that inherits currentColor and token sizes. */",
    "\t\tconst icon = (name, size) => {",
    "\t\t\tconst markup = ICON_SVG[name];",
    "\t\t\tif (!markup) return null;",
    "\t\t\treturn react.createElement(\"span\", {",
    "\t\t\t\tclassName: \"ia-icon\",",
    "\t\t\t\t\"aria-hidden\": \"true\",",
    "\t\t\t\tdangerouslySetInnerHTML: { __html: markup.replace('<svg ', `<svg width=\"${size ?? 18}\" height=\"${size ?? 18}\" `) },",
    "\t\t\t});",
    "\t\t};",
    "\t\t/* ICONS:END */",
  ].join(eol);
  return block;
}

const START = "/* ICONS:START";
const END = "/* ICONS:END */";

const source = readFileSync(clientPath, "utf-8");
const startIndex = source.indexOf(START);
const endIndex = source.indexOf(END);
if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
  console.error("generate-icons: ICONS markers not found in lib/client.js");
  console.error(`  expected a block between "${START} ..." and "${END}"`);
  process.exit(1);
}

// Match the line ending of the region being replaced, so re-running the
// generator is a byte-for-byte no-op on every platform. A region with no line
// ending at all (a one-liner) falls back to the host file's dominant ending.
const region = source.slice(startIndex, endIndex + END.length);
const eol = newlineOf(region) ?? newlineOf(source) ?? "\n";

const generated = build(eol);
const head = source.slice(0, source.indexOf("\t\t/* ICONS:START"));
const tail = source.slice(endIndex + END.length);
const next = head + generated + tail;

if (process.argv.includes("--check")) {
  if (next === source) {
    console.log(`generate-icons: up to date (${Object.keys(ICONS).length} icons)`);
    process.exit(0);
  }
  console.error("generate-icons: lib/client.js is STALE — run `node app/plugins/dsh-product-shell/scripts/generate-icons.mjs`");
  process.exit(1);
}

if (next === source) {
  console.log(`generate-icons: no change (${Object.keys(ICONS).length} icons)`);
  process.exit(0);
}
writeFileSync(clientPath, next);
console.log(`generate-icons: wrote ${Object.keys(ICONS).length} icons into lib/client.js`);
